#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt update
sudo apt install nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart