#!/usr/bin/env bash
# Make to /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx

# Create default page
echo "Hello World!" > /var/www/html/index.html


sudo ufw allow 'Nginx HTTP'

# Add redirection
new_site="https://github.com/SosMrRaziel"
sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" /etc/nginx/sites-available/default

sudo service nginx restart
