#!/usr/bin/env bash
# install HaProxy
apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install -y haproxy

cp -n /etc/haproxy/haproxy.cfg /etc/haproxy/origine

echo "ENABLED=1" | tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | tee -a /etc/default/haproxy

echo "
frontend front
		bind *:80
		default_backend back

backend back
		balance roundrobin
		server raziel-web-01 54.87.212.72:80 check
		server raziel-web-02 34.229.254.154:80 check" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
