#!/usr/bin/env bash
# install HaProxy
apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install -y haproxy

echo "ENABLED=1" | tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | tee -a /etc/default/haproxy

echo "
frontend front
    bind *:80
    default_backend back

backend back
    balance roundrobin
    server raziel-web-01 107.23.102.54:80 check
    server raziel-web-02 54.160.89.181:80 check" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
