#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

hr=0
min=1

while [ $hr -le 12 ];
do
    echo "hour: $hr"
    while [ $min -le 59 ]
    do
        echo $min
        ((min++))
    done
    min=0
    ((hr++))
done