#!/usr/bin/env bash
# a Bash script that configures the container
cp -n /etc/nginx/sites-available/default /etc/nginx/sites-available/origin
cat /etc/nginx/sites-available/origin > /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
